### ISSUE TITLE
[Countdown] Görli Rollout Tracker

### ISSUE THREAD

**Issue by 5chdn** [goerli/testnet#39]
- [x] gather validators
  - [x] afri/parity `0xe0a2bd4258d2768837baa26a28fe71dc079f84c7` (genesis)
  - [x] chris/pantheon `0x22ea9f6b28db76a7162054c05ed812deb2f519cd`
  - [x] e.g./infura `0x8b24eb4e6aae906058242d83e51fb077370c4720`
  - [x] igor/poa-network `0x000000568b9b5a365eaa767d42e74ed88915c204`
  - [x] tomasz/nethermind `0x4c2ae482593505f0163cdefc073e81c63cda4107`
  - [x] preston/prysm-labs #38 `0xd9a5179f091d85051d3c982785efd1455cec8699`
  - [x] nikola/dapowerplay `0xA8e8F14732658E4B51E8711931053a8A69BaF2B1`
- [x] regenerate genesis
  - [x] network id `5`
  - [x] chain id `5`
  - [x] alloc for faucets & validators
    - [x] afri/parity `0xe0a2bd4258d2768837baa26a28fe71dc079f84c7` 89.8m (genesis)
    - [x] chris/pantheon `0x22ea9f6b28db76a7162054c05ed812deb2f519cd` 100k
    - [x] e.g./infura `0x8b24eb4e6aae906058242d83e51fb077370c4720` 10m
    - [x] igor/poa-network `0x000000568b9b5a365eaa767d42e74ed88915c204` 10m
    - [x] tomasz/nethermind `0x4c2ae482593505f0163cdefc073e81c63cda4107` 100k (genesis)
    - [x] preston/prysm-labs #38 `0xd9a5179f091d85051d3c982785efd1455cec8699` 10m (genesis)
    - [x] nikolai/dapowerplay `0xA8e8F14732658E4B51E8711931053a8A69BaF2B1` 100k (genesis)
  - [x] some catch phrase for the extradata ;)
- [x] push the red button
  - [x] spin up the nodes
  - [x] deploy the bridges/faucets
  - [x] reset the netstats/explorers
  - [x] inform everyone to update the specs/reset their nodes
    - [x] blockscout
    - [x] explorer.goerli.net
    - [x] nethermind görli config
    - [x] pantheon görli config
    - [x] ethereumjs görli config
  - [x] update the docs

**Comment by tkstanczak** [comment]
Nethermind 0x4c2ae482593505f0163cdefc073e81c63cda4107

**Comment by lazaridiscom** [comment]
Possibly place this link: https://github.com/goerli/testnet/projects/1 into the text.

**Comment by 5chdn** [comment]
@priom please post the görli validator key here

**Comment by JohnnySheffield** [comment]
@5chdn Ready to update specs/reset nodes for explorer.goerli.net on your signal.

0xA8e8F14732658E4B51E8711931053a8A69BaF2B1 - nikola/dapowerplay

**Comment by thefallentree** [comment]
my validator address is : 0x9a66a7d5162074a0899edf2d344f1f1fd6981869

**Comment by igorbarinov** [comment]
Hi guys, what it is the process of becoming a validator on Goerli for POA?
Should we generate a mining address and submit it here?

**Comment by igorbarinov** [comment]
POA validator address is: 0x000000568b9b5a365eaa767d42e74ed88915c204

**Comment by egalano** [comment]
Infura's validator address is : 0x8b24eb4e6aae906058242d83e51fb077370c4720

**Comment by Errorific** [comment]
chris/pantheon validator address is: 0x22ea9f6b28db76a7162054c05ed812deb2f519cd

**Comment by thefallentree** [comment]
I think we should stop calling it validators,  anyone can run an node that validates. If these nodes needs to seal, then we could call it sealers ? or miners? or maybe courtier of the high clique kingdom.

**Comment by cleanunicorn** [comment]
cleanunicorn/cdili
0xc56ff35731dc01a87f1910ad73b78b4ce90ae1dd

**Comment by rstormsf** [comment]
Peppersec/Roman
0xfE97A6232df975b2386DE825b424c05E532E6FAD

**Comment by jvt2** [comment]
0xa29FEfdB00925AfFFdB74ec14bc923214F11877E

**Comment by ligi** [comment]
I think "deploy the bridges/faucets" can be ticked 
So the last thing before this can be closed is "ethereumjs görli config" - ping @holgerd77 can you help out here?

**Comment by karalabe** [comment]
Is it too late to add to the list? Sorry, was offline until today for 2 weeks. The EF can also run a validator for Görli, and also a bootnode.

PS. Bootnodes also need to be coded in into the specs AFAIK, shouldn't we gather a list of enode ids for that?

**Comment by holgerd77** [comment]
@ligi Our [client](https://github.com/ethereumjs/ethereumjs-client) is still IN DEVELOPMENT anyhow, but we have `goerli` support build in and it can be used with `--network=goerli`. Not sure if this helps? The configuration itself can be found in the [chains/goerli.json](https://github.com/ethereumjs/ethereumjs-common/blob/master/src/chains/goerli.json) of our `ethereumjs-common` library.

**Comment by ligi** [comment]
@holgerd77 great! then I think this issue can be closed as all boxes are ticked

**Comment by 5chdn** [comment]
@ligi @holgerd77 we need to update the goerli.json to match the new spec. It still uses the pre-goerli configuration.

**Comment by 5chdn** [comment]
And we are live :tada:

**Comment by jvt2** [comment]
![piramids of giza](https://user-images.githubusercontent.com/16857788/52500593-63c90b00-2bac-11e9-8b51-e4638882cc59.jpg)

**Comment by jvt2** [comment]
Building something that will be around for thousands of years

**Comment by ligi** [comment]
@thefallentree your signer seems to be offline
