### ISSUE TITLE
Berlin Validator Checklist

### ISSUE THREAD

**Issue by q9f** [goerli/testnet#76]
Berlin upgrade tracker, ref #75 https://github.com/ethereum/eth1.0-specs/pull/14 https://github.com/ethereum/pm/issues/248

Minimum client versions 
- Geth `1.10.1` https://github.com/ethereum/go-ethereum/releases/tag/v1.10.1
- OpenEthereum `v3.2.0` https://github.com/openethereum/openethereum/releases/tag/v3.2.0
- Besu `21.1.1` https://github.com/hyperledger/besu/releases/tag/21.1.1
- Nethermind `v1.10.31` https://github.com/NethermindEth/nethermind/releases/tag/1.10.31

Please confirm client and version after upgrading the validator to a Berlin-ready release.
- [x] `0x000000568b9b5a365eaa767d42e74ed88915c204` POA Network (✅ Nethermind 1.10.37)
- [x] `0x22ea9f6b28db76a7162054c05ed812deb2f519cd` ConsenSys/Besu (✅ Besu 21.1.2)
- [x] `0x4c2ae482593505f0163cdefc073e81c63cda4107` Nethermind (✅ Nethermind 1.10.44)
- [x] `0x73625f59CAdc5009Cb458B751b3E7b6b48C06f2C` Flashbots (✅ Geth 1.10.1)
- [x] `0x8b24eb4e6aae906058242d83e51fb077370c4720` Infura (✅ Geth 1.10.1)
- [x] `0x9d525e28fe5830ee92d7aa799c4d21590567b595` Goerli/Ronin (✅ OpenEthereum 3.2.0)
- [x] `0xa6dd2974b96e959f2c8930024451a30afec24203` Ethereum/Geth (✅  Geth 1.10.2-unstable)
- [x] `0xd9a5179f091d85051d3c982785efd1455cec8699` Prysmatic Labs (✅ Geth 1.10.1)
- [x] `0xe0a2bd4258d2768837baa26a28fe71dc079f84c7` Goerli/Afri (✅ Besu 21.1.2)

**Comment by karalabe** [comment]
You'll need Geth 1.10.0 stable for Berlin fork numbers. It's not released yet.

**Comment by karalabe** [comment]
@q9f Please see my updated post above

**Comment by q9f** [comment]
I'm aware. Looking forward to the call tomorrow. THanks

**Comment by jparyani** [comment]
Flashbots has updated to geth v1.10.1

**Comment by q9f** [comment]
Ok, releases are out! Go go go!
- Geth `1.10.1` https://github.com/ethereum/go-ethereum/releases/tag/v1.10.1
- OpenEthereum `v3.2.0` https://github.com/openethereum/openethereum/releases/tag/v3.2.0
- Besu `21.1.1` https://github.com/hyperledger/besu/releases/tag/21.1.1
- Nethermind `v1.10.31` https://github.com/NethermindEth/nethermind/releases/tag/1.10.31

**Comment by q9f** [comment]
6 days to go!

**Comment by roninkaizen** [comment]
done, 
thanks for reminding

**Comment by igorbarinov** [comment]
Nethermind `1.10.37` for POA validator

```
nethermind    | ======================== Nethermind initialization completed ========================
nethermind    | Version      : 1.10.37-0-068e5c399-20210312/X64-Linux/5.0.4
```

**Comment by karalabe** [comment]
EF validator on `Geth/v1.10.2-unstable-faacc8e0-20210315/linux-amd64/go1.16.2`

**Comment by roninkaizen** [comment]
prysm and EF are done from my perspective-
ready to be closed now?

**Comment by q9f** [comment]
Thanks, that is all. Hardfork ETA tomorrow morning.

**Comment by roninkaizen** [comment]
**ding** fertsch!
